version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/local/app
    ports:
      - 4000:4000
    depends_on:
      - mongo
    command: shotgun -o 0.0.0.0 -p 4000
    environment:
      - RACK_ENV=production
      - MONGOHQ_URL=mongodb://mongo/prgrphs_production
      - REDISTOGO_URL=redis://redis
    env_file:
      - ./.env
  mongo:
    image: mongo 
  redis:
    image: redis
