source 'https://rubygems.org'
gem 'sinatra'
gem 'haml'
gem 'coffee-filter'
gem 'mongoid'
gem 'omniauth-twitter'
gem 'redcarpet'
gem 'builder'
gem 'uuid'
gem 'therubyracer'
gem 'nokogiri'
gem 'redis'
gem 'redis-namespace'
gem 'redis-pool'
gem 'resque'
gem 'axlsx'
gem 'aws-sdk'
gem 'twitter'
gem 'capybara-webkit'
gem 'kaminari-mongoid'
group :development do
  gem 'shotgun'
end
